# Generated by Django 5.0.3 on 2025-05-13 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('stego_filename', models.CharField(max_length=255)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('test_type', models.CharField(choices=[('RSA', 'RSA Only'), ('RSA_LSB', 'RSA + LSB Steganography')], max_length=10)),
                ('file_size', models.PositiveIntegerField()),
                ('encryption_time', models.FloatField()),
                ('decryption_time', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('avalanche_effect', models.FloatField()),
                ('entropy_before', models.FloatField()),
                ('entropy_after', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
